###
GET http://localhost:8000/startups

###
GET http://localhost:8000/startups/7

###
GET http://localhost:8000/selection

###
GEt http://localhost:8000/startups/search?코드

###
POST  http://localhost:8000/investments
Content-Type: application/json

{
  "name": "테스트",
  "investAmount": 50000,
  "comment": "투자 테스트",
  "password": "1234",
  "startupId": 2
}